Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;
using PHotoFockus.Data.models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PHotoFockus.Controllers
{
    public class AboutUsController : Controller
    {
        public AboutUsController()
        {

        }

        public ViewResult AboutUsPage()
        {
            return View();
        }
    }
}

Controllers/FockusCartController.cs
using Microsoft.AspNetCore.Mvc;
using PHotoFockus.Data;
using PHotoFockus.Data.Interfaces;
using PHotoFockus.Data.models;
using PHotoFockus.Data.Repository;
using PHotoFockus.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PHotoFockus.Controllers
{
    public class FockusCartController : Controller
    {
        private readonly IAllProducts _prodRep;
        private readonly FockusCart _fockusCart;
        private readonly AppDBContent _appDBContent;

        public int ID { get; set; }

        public FockusCartController(IAllProducts prodRep, FockusCart fockusCart, AppDBContent appDBContent)
        {
            _prodRep = prodRep;
            _fockusCart = fockusCart;
            _appDBContent = appDBContent;
        }

        public ViewResult Index()
        {
            var Items = _fockusCart.GetFockusItem();
            _fockusCart.listFockusItem = Items;

            var obj = new FockusCartViewModels
            {
                fockusCart = _fockusCart
            };

            return View(obj);
        }

        public ViewResult AboutProduct(int id)
        {
            var AboutProdItem = _appDBContent.Product.Find(id);

            _fockusCart._aboutProd = AboutProdItem;

            var obj = new FockusCartViewModels
            {
                fockusCart = _fockusCart
            };

            return View(obj);
        }

        public RedirectToActionResult aboutProd(int id)
        {
            ID = id;
            var item = _prodRep.Products.FirstOrDefault(i => i.id == id);

            if (item != null)
            {
                _fockusCart.AboutProduct(item);
            }

            return RedirectToAction("AboutProduct");
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _prodRep.Products.FirstOrDefault(i => i.id == id);

            if (item != null)
            {
                _fockusCart.AddToCart(item);
            }

            return RedirectToAction("index");
        }

        public RedirectToActionResult removeToCart(int id)
        {
            _fockusCart.RemoveToCart(id);
            return RedirectToAction("index");
        }

        public RedirectToActionResult removeToCartAll()
        {
            _fockusCart.RemoveToCartAll();

            return RedirectToAction("index", "Home");
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using PHotoFockus.Data.Interfaces;
using PHotoFockus.Data.models;
using PHotoFockus.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PHotoFockus.Controlers
{
    public class ProductsController : Controller
    {
        private readonly IAllProducts _AllProduct;
        private readonly IProductsCategory _AllCategories;
        private readonly IAddProduct _addProduct;

        public ProductsController(IAllProducts iAllProduct, IAddProduct addProduct, IProductsCategory iProdCat)
        {
            _AllProduct = iAllProduct;
            _AllCategories = iProdCat;
            _addProduct = addProduct;
        }

        [Route("Products/List")]
        [Route("Products/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                products = _AllProduct.Products.OrderBy(i => i.id);
            }
            else
            {
                if(string.Equals("clothes", category, StringComparison.OrdinalIgnoreCase))
                {
                    products = _AllProduct.Products.Where(i => i.Categories.CategoryName.Equals("Вещи")).OrderBy(i => i.id);
                }
                else if (string.Equals("stationery", category, StringComparison.OrdinalIgnoreCase))
                {
                    products = _AllProduct.Products.Where(i => i.Categories.CategoryName.Equals("Канцтовары")).OrderBy(i => i.id);
                }

                currCategory = _category;
            }

            
            var carObj = new ProductsViewModels
            {
                AllProducts = products,
                CurrCategory = currCategory
            };

            ViewBag.Title = "Страница с продуктами";

            return View(carObj);
        }

        public IActionResult AdminPass_6742()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AdminPass_6742(AddNewProduct add)
        {
            if (ModelState.IsValid)
            {
                _addProduct.AddProduct(add);

            }

            return View(add);
        }

        public IActionResult AddComplete()
        {
            ViewBag.Message = "Продукт Добавлен!";

            return View();
        }
    }
}

Views/Shared/AboutUsLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PHokus</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sticky-footer/">
</head>

<style>

    element.style {
    }

    .dropdown, .dropend, .dropstart, .dropup {
        position: relative;
    }

    .ml-auto, .mx-auto {
        margin-left: unset;
    }

    /*.container{
        max-width: 800px;
    }*/

    .site-header {
        background-color: rgba(0, 0, 0, .85);
        /*-webkit-backdrop-filter: saturate(180%) blur(20px);*/
       /* backdrop-filter: saturate(180%) blur(20px);*/
    }

        .site-header a {
            color: #999;
            transition: ease-in-out color .15s;
        }

    a.py-2.d-none.d-md-inline-block {
    }

    .site-header a:hover {
        color: #fff;
        text-decoration: none;
    }

    a{
        text-decoration: none;
    }

    .pb-1, .py-1 {
        padding-bottom: .25rem !important;
    }

    .pt-1, .py-1 {
        padding-top: .25rem !important;
    }

    .sticky-top {
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        z-index: 1020;
    }

    article, aside, dialog, figcaption, figure, footer, header, hgroup, main, nav, section {
        display: block;
    }

    *, ::after, ::before {
        box-sizing: border-box;
    }

    user agent stylesheet
    nav {
        display: block;
    }

    body {
        margin: 0;
        font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
        font-size: 1.5rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        text-align: left;
        background-color: #fff;
    }

    :root {
        --blue: #007bff;
        --indigo: #6610f2;
        --purple: #6f42c1;
        --pink: #e83e8c;
        --red: #dc3545;
        --orange: #fd7e14;
        --yellow: #ffc107;
        --green: #28a745;
        --teal: #20c997;
        --cyan: #17a2b8;
        --white: #fff;
        --gray: #6c757d;
        --gray-dark: #343a40;
        --primary: #007bff;
        --secondary: #6c757d;
        --success: #28a745;
        --info: #17a2b8;
        --warning: #ffc107;
        --danger: #dc3545;
        --light: #f8f9fa;
        --dark: #343a40;
        --breakpoint-xs: 0;
        --breakpoint-sm: 576px;
        --breakpoint-md: 768px;
        --breakpoint-lg: 992px;
        --breakpoint-xl: 1200px;
        --font-family-sans-serif: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
        --font-family-monospace: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
    }

    html {
        font-family: sans-serif;
        line-height: 1.15;
        -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
        -ms-overflow-style: scrollbar;
        -webkit-tap-highlight-color: transparent;
    }

    *, ::after, ::before {
        box-sizing: border-box;
    }

    *, ::after, ::before {
        box-sizing: border-box;
    }
</style>

<body>
    <nav class="site-header sticky-top py-1">
        <div class="container d-flex flex-column flex-md-row  col-md-5 justify-content-between">
            <a class="py-2" asp-controller="Home" asp-action="index">
                <svg xmlns="http://www.w3.org/2000/svg" width="34" height="44" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="d-block mx-auto">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="14.31" y1="8" x2="20.05" y2="17.94"></line>
                    <line x1="9.69" y1="8" x2="21.17" y2="8"></line>
                    <line x1="7.38" y1="12" x2="13.12" y2="2.06"></line>
                    <line x1="9.69" y1="16" x2="3.95" y2="6.06"></line>
                    <line x1="14.31" y1="16" x2="2.83" y2="16"></line>
                    <line x1="16.62" y1="12" x2="10.88" y2="21.94"></line>
                </svg>
            </a>
            
            <a class="py-2 d-none d-md-inline-block" asp-controller="Products" asp-action="List">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Товары</font>
                </font>
            </a>

            <a class="py-2 d-none d-md-inline-block" asp-controller="AboutUs" asp-action="AboutUsPage">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Про нас</font>
                </font>
            </a>

            <a class="py-2 d-none d-md-inline-block" href="#">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Поддержка</font>
                </font>
            </a>

            <a class="py-2 d-none d-md-inline-block" href="#">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Корзина</font>
                </font>
            </a>
        </div>
    </nav>

    <div>
        <div class="row">
   <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse" style="">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Приборная панель
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Заказы
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Товары
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Клиенты
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Отчеты
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Интеграции
            </font></font></a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Сохраненные отчеты</font></font></span>
          <a class="link-secondary" href="#" aria-label="Добавить новый отчет">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Текущий месяц
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Последняя четверть
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Социальная активность
            </font></font></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
              Распродажа на конец года
            </font></font></a>
          </li>
        </ul>
      </div>
    </nav>
</div>
        @RenderBody()
    </div>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Поместите сюда липкий нижний колонтитул.</font></font></span>
        </div>
    </footer>

    <script src="~/js/bootstrap.min.js"></script>
    
</body>
</html>

Views/Shared/AllProduct.cshtml
@model PHotoFockus.Data.models.Product

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.Name" />
    <h2 calss="featurette-heading">@Model.Name</h2>
    <p class="lead">@Model.ShortDescription</p>
    <p class="lead">Цена: @Model.Price.ToString("c")</p>
    @*col-lg-4 <p><a class="btn btn-warning" asp-controller="FockusCart" asp-action="AboutProduct" asp-route-id="@Model.id">Подробнее</a></p> *@
    <p><a class="btn btn-lg btn-primary" asp-controller="FockusCart" asp-action="AboutProduct" asp-route-id="@Model.id" role="button">Подробнее</a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PHokus</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sticky-footer/">
</head>

<style>

    element.style {
    }

    .dropdown, .dropend, .dropstart, .dropup {
        position: relative;
    }

    .ml-auto, .mx-auto {
        margin-left: unset;
    }

    /*.container{
        max-width: 800px;
    }*/

    .site-header {
        background-color: rgba(0, 0, 0, .85);
        /*-webkit-backdrop-filter: saturate(180%) blur(20px);*/
       /* backdrop-filter: saturate(180%) blur(20px);*/
    }

        .site-header a {
            color: #999;
            transition: ease-in-out color .15s;
        }

    a.py-2.d-none.d-md-inline-block {
    }

    .site-header a:hover {
        color: #fff;
        text-decoration: none;
    }

    a{
        text-decoration: none;
    }

    .pb-1, .py-1 {
        padding-bottom: .25rem !important;
    }

    .pt-1, .py-1 {
        padding-top: .25rem !important;
    }

    .sticky-top {
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        z-index: 1020;
    }

    article, aside, dialog, figcaption, figure, footer, header, hgroup, main, nav, section {
        display: block;
    }

    *, ::after, ::before {
        box-sizing: border-box;
    }

    user agent stylesheet
    nav {
        display: block;
    }

    body {
        margin: 0;
        font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
        font-size: 1.5rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        text-align: left;
        background-color: #fff;
    }

    :root {
        --blue: #007bff;
        --indigo: #6610f2;
        --purple: #6f42c1;
        --pink: #e83e8c;
        --red: #dc3545;
        --orange: #fd7e14;
        --yellow: #ffc107;
        --green: #28a745;
        --teal: #20c997;
        --cyan: #17a2b8;
        --white: #fff;
        --gray: #6c757d;
        --gray-dark: #343a40;
        --primary: #007bff;
        --secondary: #6c757d;
        --success: #28a745;
        --info: #17a2b8;
        --warning: #ffc107;
        --danger: #dc3545;
        --light: #f8f9fa;
        --dark: #343a40;
        --breakpoint-xs: 0;
        --breakpoint-sm: 576px;
        --breakpoint-md: 768px;
        --breakpoint-lg: 992px;
        --breakpoint-xl: 1200px;
        --font-family-sans-serif: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
        --font-family-monospace: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
    }

    html {
        font-family: sans-serif;
        line-height: 1.15;
        -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
        -ms-overflow-style: scrollbar;
        -webkit-tap-highlight-color: transparent;
    }

    *, ::after, ::before {
        box-sizing: border-box;
    }

    *, ::after, ::before {
        box-sizing: border-box;
    }
</style>

<body>
    <nav class="site-header sticky-top py-1">
        <div class="container d-flex flex-column flex-md-row  col-md-5 justify-content-between">
            <a class="py-2" asp-controller="Home" asp-action="index">
                <svg xmlns="http://www.w3.org/2000/svg" width="34" height="44" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="d-block mx-auto">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="14.31" y1="8" x2="20.05" y2="17.94"></line>
                    <line x1="9.69" y1="8" x2="21.17" y2="8"></line>
                    <line x1="7.38" y1="12" x2="13.12" y2="2.06"></line>
                    <line x1="9.69" y1="16" x2="3.95" y2="6.06"></line>
                    <line x1="14.31" y1="16" x2="2.83" y2="16"></line>
                    <line x1="16.62" y1="12" x2="10.88" y2="21.94"></line>
                </svg>
            </a>
            
            <a class="py-2 d-none d-md-inline-block" asp-controller="Products" asp-action="List">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Товары</font>
                </font>
            </a>

            <a class="py-2 d-none d-md-inline-block" asp-controller="AboutUs" asp-action="AboutUsPage">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Про нас</font>
                </font>
            </a>

            <a class="py-2 d-none d-md-inline-block" href="#">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Поддержка</font>
                </font>
            </a>

            <a class="py-2 d-none d-md-inline-block" href="#">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">Корзина</font>
                </font>
            </a>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Поместите сюда липкий нижний колонтитул.</font></font></span>
        </div>
    </footer>

    <script src="~/js/bootstrap.min.js"></script>
    
</body>
</html>