ViewModels/AboutProductViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PHotoFockus.Data.models;

namespace PHotoFockus.ViewModels
{
    public class AboutProductViewModels
    {
        public AboutProd aboutprod { get; set; }
    }
}

ViewModels/FockusCartViewModels.cs
using PHotoFockus.Data.models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PHotoFockus.ViewModels
{
    public class FockusCartViewModels
    {
        public FockusCart fockusCart { get; set; }
    }
}

Controllers/AboutProductController.cs
using Microsoft.AspNetCore.Mvc;
using PHotoFockus.Data;
using PHotoFockus.Data.Interfaces;
using PHotoFockus.Data.models;
using PHotoFockus.Data.Repository;
using PHotoFockus.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PHotoFockus.Controllers
{
    public class AboutProductController : Controller
    {
        public Product product;
        public AppDBContent _appDB;
        
        public AboutProductController (AppDBContent appDB)
        {
            _appDB = appDB;
        }

        public ViewResult index()
        {
            return View();
        }

        public RedirectToActionResult aboutProduct(int id)
        {
            var item = _appDB.Product.Find(id);

            if (item != null)
                product = new Product
                {
                    Name = item.Name,
                    LongDescription = item.LongDescription,
                    img = item.img,
                    Price = item.Price
                };
            
            return RedirectToAction("index");
        }
    }
}

Controllers/FockusCartController.cs
using Microsoft.AspNetCore.Mvc;
using PHotoFockus.Data;
using PHotoFockus.Data.Interfaces;
using PHotoFockus.Data.models;
using PHotoFockus.Data.Repository;
using PHotoFockus.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PHotoFockus.Controllers
{
    public class FockusCartController : Controller
    {
        private readonly IAllProducts _prodRep;
        private readonly FockusCart _fockusCart;
        private readonly AppDBContent _appDBContent;

        public int ID { get; set; }

        public FockusCartController(IAllProducts prodRep, FockusCart fockusCart, AppDBContent appDBContent)
        {
            _prodRep = prodRep;
            _fockusCart = fockusCart;
            _appDBContent = appDBContent;
        }

        public ViewResult Index()
        {
            var Items = _fockusCart.GetFockusItem();
            _fockusCart.listFockusItem = Items;

            var obj = new FockusCartViewModels
            {
                fockusCart = _fockusCart
            };

            return View(obj);
        }

        public ViewResult AboutProduct(int id)
        {
            var AboutProdItem = _appDBContent.Product.Find(id);

            _fockusCart._aboutProd = AboutProdItem;

            var obj = new FockusCartViewModels
            {
                fockusCart = _fockusCart
            };

            return View(obj);
        }

        public RedirectToActionResult aboutProd(int id)
        {
            ID = id;
            var item = _prodRep.Products.FirstOrDefault(i => i.id == id);

            if (item != null)
            {
                _fockusCart.AboutProduct(item);
            }

            return RedirectToAction("AboutProduct");
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _prodRep.Products.FirstOrDefault(i => i.id == id);

            if (item != null)
            {
                _fockusCart.AddToCart(item);
            }

            return RedirectToAction("index");
        }

        public RedirectToActionResult removeToCart(int id)
        {
            _fockusCart.RemoveToCart(id);
            return RedirectToAction("index");
        }

        public RedirectToActionResult removeToCartAll()
        {
            _fockusCart.RemoveToCartAll();

            return RedirectToAction("index", "Home");
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using PHotoFockus.Data;
using PHotoFockus.Data.Interfaces;
using PHotoFockus.Data.models;
using System.Net.Mail;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PHotoFockus.Controllers
{
    public class OrderController : Controller
    {
        private readonly AppDBContent _appDBContent;
        private readonly IAllOrder _allOrders;
        private readonly FockusCart _shopCart;

        public OrderController(IAllOrder allOrders, FockusCart shopCart, AppDBContent appDBContent)
        {
            _allOrders = allOrders;
            _shopCart = shopCart;
            _appDBContent = appDBContent;
        }


        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            _shopCart.listFockusItem = _shopCart.GetFockusItem();

            if (_shopCart.listFockusItem.Count == 0)
            {
                ModelState.AddModelError("", "У вас должны быть товары");
            }

            if (ModelState.IsValid)
            {
                string body = "<p>-----</p><h2>Заказ Сделал(а)</h2> <p>Имя Фамилия: " + order.name + " " + order.surename + "</p>" + "<p>номр тел.: " + order.phone + "</p>" + "<p>-----</p>";

                for(int i = 0; i < _shopCart.listFockusItem.Count; i++){
                    body += "<h2>" + _shopCart.listFockusItem[i].product.Name + " " + _shopCart.listFockusItem[i].product.ShortDescription + "</h2>" + "<p> Цена: " + _shopCart.listFockusItem[i].product.Price.ToString() + "</p>" + "<p>" + _shopCart.listFockusItem[i].product.img + "</p>" + "<p>-----</p>";
                }

                

                // <img class="img-thumbnail" src="@Model.img" alt="@Model.Name" />

                _allOrders.CreateOrder(order);
                _shopCart.SendMail(order.email, order.name, "Новый заказ", body);
                return RedirectToAction("Complete");
            }
            
            return View(order);
        }


        public IActionResult Complete(string mail, string name, string subject)
        {
            ViewBag.Message = "Заказ успешно обработан";
            _shopCart.listFockusItem = new List<FockusCartItem> { };
            
            return View();
        }
    }
}

Views/FockusCart/AboutProduct.cshtml
@model FockusCartViewModels

<style>
    .featurette-divider{
        margin: 5rem 0;
    }
</style>

<div class="container marketing">

    <hr class="featurette-divider">

    <div class="row featurette">

        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">@Model.fockusCart._aboutProd.Name <span class="text-muted">@Model.fockusCart._aboutProd.ShortDescription</span></h2>
            <p class="lead">@Model.fockusCart._aboutProd.LongDescription</p>
            
        </div>

        <div class="col-md-5 order-md-1">
            <img class="img-thumbnail" src="@Model.fockusCart._aboutProd.img" alt="@Model.fockusCart._aboutProd.Name"/>
            
        </div>

    </div>

    <div class="row featurette">

        <div class="col-md-3 order-md-2">
            <h2 class="featurette-heading">Цена: @Model.fockusCart._aboutProd.Price</h2>
        </div>
        
        <hr class="featurette-divider">

        <div class="col-md-9 order-md-1 mt-2">
            <p><a class="btn btn-lg btn-primary" asp-controller="FockusCart" asp-action="addToCart" asp-route-id="@Model.fockusCart._aboutProd.id" role="button">В корзину</a></p>        

        </div>

    </div>
    
</div>

@* <img class="img-thumbnail" src="@Model.fockusCart._aboutProd.img" alt="@Model.fockusCart._aboutProd.Name" />
            <h2>@Model.fockusCart._aboutProd.Name</h2>
            <p>@Model.fockusCart._aboutProd.LongDescription</p>
            <p>Цена: @Model.fockusCart._aboutProd.Price</p>
            <p><a class="btn btn-warning" asp-controller="FockusCart" asp-action="addToCart" asp-route-id="@Model.fockusCart._aboutProd.id">Добавть в карзину</a></p> *@

Views/FockusCart/index.cshtml
@model FockusCartViewModels

<div class="container marketing">
    @foreach (var el in Model.fockusCart.listFockusItem)
    {
        <hr class="featurette-divider">
            <b>Продукт:</b> @el.product.Name<br />
            <p><img src="@el.product.img" alt="@el.product.Name"></p>
            <b>Цена:</b> @el.product.Price.ToString("c")
            <p><a class="btn btn-danger " asp-controller="FockusCart" asp-action="removeToCart" asp-route-id="@el.id">Удалить продукт</a></p>
        
    }
    <hr class="featurette-divider md-5 mt-5">
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оформить заказ</a>
</div>